### PR TITLE
Remove underscore in favor of object-assign polyfill and lodash.template

### LINKED ISSUE #27: Remove underscore dependency
Underscore is a bit heavy for a dependency. We're only using it for it's `template` function and `extend`. Should be straight forward to remove.

### PR DESCRIPTION
**Pull request by mvattuone**
Potentially closes https://github.com/18F/glossary/issues/27

I would prefer to not include _any_ dependencies, but Object.assign and template literals both require some additional work (i.e. Babel and related updates due to PhantomJS being in tests). This seemed like the simplest, most readable solution. 

Happy to use regular string concatenation, but that's probably going to be pretty brittle.

### CODE REVIEW

**Comment by afeld** [comment]
Hmm. Not sure there's a lot of advantage in swapping one dependency for two. I think I'd prefer using Babel to support `Object.assign` instead of just using different non-standardized functions. Thanks anyway!

**Comment by mvattuone** [comment]
You're going to need to update your testing setup a lot if you want Babel.
I tried.

**Comment by afeld** [comment]
Ah, bummer. In that case, will merge these to get the (small, but not nothing) size savings. Thanks!

**Comment by mvattuone** [comment]
Thanks for that - I'll make an issue outlining the issues I ran into since
you'll want to update eventually, anyway. Happy to help w that if it makes
sense.


Mike

**Comment by afeld** [comment]
Cool - posting here, in #27, or a new issue is fine. Thanks!

**Pull request merged**
